### ISSUE TITLE
The action doesn't work anymore with new Asana URL format

### ISSUE THREAD

**Issue by nicooprat** [Asana/create-app-attachment-github-action#40]
Regarding this announcement: https://forum.asana.com/t/upcoming-new-v1-asana-url-format-in-the-browser/1011489

URL formats changed from `https://app.asana.com/1/xxx/xxx` to  `https://app.asana.com/1/xxx/project/xxx/task/xxx`.

I guess this action can't match this new format

**Comment by arnaudvalle** [comment]
The issue seems fixed now? I can see some comments being added to my tasks again now... 🤔

**Comment by devor** [comment]
We are still having issues with this change, but not consistently. Only about 80% of the time.

**Comment by lonnylot** [comment]
We are also having an issue.

**Comment by tomikng** [comment]
Same here

**Comment by ychartsmatt** [comment]
We've been having the same issue. Was thinking about forking and fixing, but it looks like most of the work is done in the api endpoint at https://github.integrations.asana.plus/custom/v1 according to `src/constants/requests.ts`. However, that url 404s now.

**Comment by wikando-aa** [comment]
We experiencing a similar issue. It seems the action's URL parsing is too restrictive and only supports the 'long' project-context URLs.

When using the 'Copy task link' feature in the Asana UI, we get the 'Short/Global' format that is currently not recognized. Here is a breakdown of the formats that should be supported:

**Currently Supported (Long):**
[https://app.asana.com/{routing_version}/{workspace_id}/project/{project_id}/task/{task_id}](https://app.asana.com/%7Brouting_version%7D/%7Bworkspace_id%7D/project/%7Bproject_id%7D/task/%7Btask_id%7D)

**Not Supported (Short/Global - from 'Copy Link' button):** [https://app.asana.com/{routing_version}/{workspace_id}/task/{task_id}](https://app.asana.com/%7Brouting_version%7D/%7Bworkspace_id%7D/task/%7Btask_id%7D)

**Not Supported (Alternative Short):**
[https://app.asana.com/0/{workspace_id}/{task_id}](https://app.asana.com/0/%7Bworkspace_id%7D/%7Btask_id%7D) (as mentioned by the OP)

The key is that the `{project_id} `should be optional in the regex. The `{task_id}` is the only essential part for creating the attachment. It would be great if the action could support all standard Asana URL patterns.

**Comment by xSAVIKx** [comment]
we see the same problem with `Copy link` not being supported. would be great if Asana can support this
